<?php
namespace app\admin\controller;

use app\admin\library\BaseController;
use app\admin\model\UserModel;

class User extends BaseController
{
    public $searchFields = ['id','mobile'];
    public $UserModel = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->UserModel = new UserModel();
    }

    //获取列表
    public function getData()
    {
        try{
            $condition = $this->getPageRows();
            $condition['where'] = $this->filterSearchFields($this->searchFields);
            $data['lists'] =  $this->UserModel->diySelect($condition)->select();
            $data['total'] =  $this->UserModel->diyCount($condition)->count();
            $this->assembleTableData('200', 'success', $data);
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->UserModel->where('id',$post)->find();
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

    // 修改
    public function  edit()
    {
        $mustFields = ['id','mobile','user_name','user_money'];
        $extFields = ['head_img','sex','status','birthday'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $rec = UserModel::get(['id' => $param['id']]);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }

        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();

    }

    //添加
    public function add()
    {
        $mustFields = ['mobile','user_name','user_money'];
        $extFields = ['head_img','sex','status','birthday'];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $param['create_time'] = date('Y-m-d H:i:s');
            if ($this->UserModel->save($param)) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    //删除
    public  function delete()
    {
        try {
            $post = $this->request->post('id');
            $this->UserModel->destroy($post);
            $this->ret['code'] = 200;
            $this->ret['msg'] = 'success';
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

}