<?php


namespace app\app\controller;

use think\Controller;
use think\Db;

class Base extends Controller
{
    protected $ret = ['code' => -1, 'msg' => '', 'data' => null];
    
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->authHandle();
    }

    protected function authHandle()
    {
        $path = '/' . $this->request->path() . '/';
        $noLogin = [
            '/app/login/doit/',
            '/app/login/register/',
            '/app/login/forget/',
            '/app/login/code/',
        ];
        $direct = true;
        foreach ($noLogin as $s) {
            if (substr($path, 0, strlen($s)) == $s) {
                $direct = false;
            }
        }
        if ($direct) {
            $token = $this->request->header('token');
            if (empty($token)) {
                $this->ret['code'] = 300;
                $this->ret['msg'] = '请登录';
                $this->outPutJson();
            }else{
                $user = Db::table('user')->where('token',$token)->find();
                if($user['token']){
                    define('USERID',$user['id']);
                }else{
                    $this->ret['code'] = 500;
                    $this->ret['msg'] = '登录失败，请重新登录';
                    $this->outPutJson();
                }
            }
        }
    }

    public  function receiveParam($mustFields,$extFields ,$doTrim = true)
    {
        $doTrim = $doTrim? 'trim':null;
        if (!is_array($mustFields)) {
            $mustFields = [$mustFields];
        }

        if (!is_array($extFields)) {
            $extFields = [$extFields];
        }
        foreach ($mustFields as $field) {
            $mv = $this->request->param($field, '', $doTrim);
            if ($mv === '') {
                throw new \Exception($field . ':该参数不能为空', 500);
            }
            $param[$field] = $mv;
        }
        foreach ($extFields as $field) {
            $ev = $this->request->param($field, '', $doTrim);
            $param[$field] = $ev;
        }

        return $param;
    }

    protected function outPutJson( $un = false, $exit = true )
    {
        echo $un? json_encode($this->ret, JSON_UNESCAPED_UNICODE):json_encode($this->ret);
        if ( $exit ) {
            exit();
        }
    }

    public function filterSearchFields($searchFields)
    {
        $data = [];
        foreach ( $searchFields as $filed ) {
            $v = $this->request->param($filed);
            if ( trim($v) === '' ) {
                continue;
            }
            $data[$filed] = $v;
        }
        return $data;
    }

    public function getPageRows($dpage = 1, $drows = 10)
    {
        $page = $this->request->post('pageNum', $dpage, 'intval');
        $rows = $this->request->post('pageSize', $drows, 'intval');
        $this->ret['data']['pageNum'] = (int)$page;
        $this->ret['data']['pageSize'] = (int)$rows;
        return ['page' => $page, 'limit' => $rows];
    }

    public function assembleTableData($code, $msg, $data)
    {
        $this->ret['code'] = $code;
        $this->ret['msg'] = $msg;
        $this->ret['data']['lists'] = $data['lists'];
        $this->ret['data']['total'] = (int)$data['total'];
        $this->ret['data']['pages'] = (int)ceil($data['total']/$this->ret['data']['pageSize']);
    }
}