<?php

namespace app\app\controller;

use app\admin\model\DoctorModel;

class Doctor extends Base
{
    public $searchFields = ['id','status'];
    public $DoctorModel = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->DoctorModel = new DoctorModel();
    }
    //获取列表
    public function getData()
    {
        $condition = $this->getPageRows();
        $condition['where'] = $this->filterSearchFields($this->searchFields);
        $condition['where']['status'] =1;
        $condition['field']= 'id,type,doctor_name,img,brief';
        $condition['order'] = ['create_time'=>'desc'];
        $data['lists'] =  $this->DoctorModel->diySelect($condition)->select();
        $data['total'] =  $this->DoctorModel->diyCount($condition)->count();
        $this->assembleTableData('200', 'success', $data);
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->DoctorModel
            ->field('id,doctor_name,type,img,brief,doctor_item,desc,tag')
            ->where('id',$post)->find();
        $data['doctor_item'] = explode('--',$data['doctor_item']);
        $data['tag'] = explode('--',$data['tag']);
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

}