<?php

namespace app\app\controller;
use app\admin\model\NewsModel;

class News extends Base
{
    public $searchFields = ['id','status'];
    public $NewsModes = [];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->NewsModes = new NewsModel();
    }

    //获取列表
    public function getData()
    {
        $condition = $this->getPageRows();
        $condition['where'] = $this->filterSearchFields($this->searchFields);
        $condition['where']['status'] = 1;
        $condition['order'] = ['create_time'=>'desc'];
        $data['lists'] =  $this->NewsModes->diySelect($condition)->select();
        $data['total'] =  $this->NewsModes->diyCount($condition)->count();
        $this->assembleTableData('200', 'success', $data);
        $this->outPutJson();
    }

    //查询单个详情
    public function getDataById()
    {
        $post = $this->request->post('news_id');
        $data =   $this->NewsModes->where('id',$post)->find();
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }
}