<?php


namespace app\app\controller;
use app\admin\model\TjMemberModel;

class TjMember extends Base
{
    protected  $TjMemberModel = [];
    protected  $searchFields = ['id','user_id'];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
         $this->TjMemberModel =   new TjMemberModel();
    }

    public function getData()
    {
        $condition = $this->getPageRows();
        $condition['where'] =['user_id'=>USERID];
        $condition['field'] =['id','user_id','name','mobile','sex','height','weight','birthday','city','city_num','address'];
        $condition['order'] = ['create_time'=>'desc'];
        $data['lists'] =  $this->TjMemberModel->diySelect($condition)->select();
        $data['total'] =  $this->TjMemberModel->diyCount($condition)->count();
        foreach ($data['lists'] as $k => &$v )
        {
            $v['city_num'] = explode('--',$v['city_num']);
        }
        $this->assembleTableData('200', 'success', $data);
        $this->outPutJson();
    }

    public function add()
    {
        $mustFields = ['name','mobile','sex','height','weight','birthday','city','city_num','address'];
        $extFields = [];
        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $param['user_id'] = USERID;
            $param['create_time'] = date('Y-m-d H:i:s',time());
            $param['city_num'] = implode('--',$param['city_num']);
            foreach ( $param as $k => $v ) {
                $this->TjMemberModel->$k = $v;
            }
            if ($this->TjMemberModel->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    public function  edit()
    {
        $mustFields = ['id','name','mobile','sex','height','weight','birthday','city','city_num','address'];
        $extFields = [];

        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $rec = TjMemberModel::get(['id' => $param['id']]);
            $param['city_num'] = implode('--',$param['city_num']);
            foreach ( $param as $k => $v ) {
                $rec->$k = $v;
            }
            if ($rec->save()) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '编辑成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '编辑失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->TjMemberModel->where('id',$post)->find();
        $data['city_num'] =   explode('--',$data['city_num']);
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }
}