<?php


namespace app\app\controller;


use app\admin\model\TjOrderModel;
use think\Db;

class TjOrder extends Base
{
    public $searchFields = ['id','order_status','user_id'];
    public $TjOrderModel = [];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->TjOrderModel =   new  TjOrderModel();
    }

    public function getData()
    {
        $condition = $this->getPageRows();
        $condition['where'] =['user_id'=>USERID];
        $condition['where'] =['is_del'=>0];
        $condition['order'] = ['create_time'=>'desc'];
        $condition['field'] = ['id','user_id','order_sn','order_status','goods_id','goods_name','goods_img','goods_item','goods_price','goods_num','pay_fee','pay_time','create_time','appointment'];
        $data['lists'] =  $this->TjOrderModel->diySelect($condition)->select();
        $data['total'] =  $this->TjOrderModel->diyCount($condition)->count();
        $this->assembleTableData('200', 'success', $data);
        $this->outPutJson();
    }

    public function getDataById()
    {
        $post = $this->request->post('id');
        $data =   $this->TjOrderModel
            ->field('id,user_id,order_sn,order_status,goods_id,goods_name,goods_img,goods_item,goods_price,goods_num,pay_fee,address,pay_time,create_time,appointment')
            ->where('id',$post)->find();
        if($data == ''){
            $this->ret['code'] = 500;
            $this->ret['msg'] = '订单不存在';
            $this->outPutJson();
        }
        $data['goods_item'] = explode('--',$data['goods_item']);
        $this->ret['code'] = 200;
        $this->ret['data']= $data;
        $this->ret['msg'] = 'success';
        $this->outPutJson();
    }

    public function add()
    {
        $mustFields = ['goods_id','goods_num','address'];
        $extFields = [];
        try {
            $param = $this->receiveParam($mustFields, $extFields);
            $goodsData = Db::table('tj_goods')->where('id',$param['goods_id'])->find();
            if($goodsData == '') {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '该商品不存在';
                $this->outPutJson();
            }

            $param['user_id'] = USERID;
            $param['order_sn'] = date('Ymd') . str_pad(mt_rand(1, 99999), 5, '0', STR_PAD_LEFT);
            $param['order_status'] = 0;
            $param['goods_name'] =  $goodsData['goods_name'] ;
            $param['address'] = implode('--',$param['address']);
            $param['goods_img'] = explode('--',$goodsData['img'])[0] ;
            $param['goods_item'] = $goodsData['goods_item'] ;
            $param['goods_price'] = $goodsData['goods_price'] ;
            $param['pay_fee'] = $goodsData['goods_price'] * $param['goods_num'] ;
            $param['create_time'] = date('Y-m-d H:i:s');
            if ($this->TjOrderModel->save($param)) {
                $this->ret['code'] = 200;
                $this->ret['msg'] = '添加成功';
            } else {
                $this->ret['code'] = 500;
                $this->ret['msg'] = '添加失败';
            }
        } catch (\Exception $ex) {
            $this->ret['code'] = 500;
            $this->ret['msg'] = $ex->getMessage();
        }
        $this->outPutJson();
    }

}