DROP TABLE if EXISTS `shop_goods` ;
CREATE TABLE `shop_goods` (
  `goods_id` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `cat_id` smallint(5) unsigned NOT NULL DEFAULT '0'COMMENT '商品分类',
  `goods_sn` varchar(60) NOT NULL DEFAULT '' COMMENT '商品货号',
  `goods_name` varchar(120) NOT NULL DEFAULT '' COMMENT '商品名称',
  `click_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '点击次数',
  `goods_number` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '商品库存数量',
  `goods_weight` decimal(10,3) unsigned NOT NULL DEFAULT '0.000' COMMENT '商品重量',
  `shop_price` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '商品单价',
  `keywords` varchar(255) NOT NULL DEFAULT '' COMMENT '关键词描述，搜索用',
  `goods_brief` varchar(255) NOT NULL DEFAULT '' COMMENT '商品描述',
  `goods_desc` text NOT NULL COMMENT '商品详情',
  `goods_thumb` varchar(255) NOT NULL DEFAULT '' COMMENT '商品小图',
  `goods_img` varchar(255) NOT NULL DEFAULT '' COMMENT '商品图片',
  `is_on_sale` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '是否上架 1=上架  0=下架',
  `sort_order` smallint(4) unsigned NOT NULL DEFAULT '100' COMMENT '商品排序',
  `is_delete` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `is_baoyou` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '是否包邮',
  `youfei_fee` decimal(10,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '邮费',
  `is_best` tinyint(1) unsigned NOT NULL DEFAULT '0'  COMMENT '精品',
  `is_new` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '新品',
  `is_hot` tinyint(1) unsigned NOT NULL DEFAULT '0' COMMENT '热销',
  `add_time` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '添加时间',
  `last_update` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`goods_id`),
  UNIQUE KEY `goods_sn` (`goods_sn`) USING BTREE,
  KEY `cat_id` (`cat_id`) USING BTREE,
  KEY `goods_weight` (`goods_weight`) USING BTREE,
  KEY `goods_number` (`goods_number`) USING BTREE,
  KEY `sort_order` (`sort_order`) USING BTREE
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT '商品表';